name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build the Docker image
      run: |
        IMAGE_NAME=my-docker-image
        IMAGE_TAG=$(date +%Y%m%d%H%M%S)  # Generate a timestamp-based tag
        docker build -t ghcr.io/cipherforge-labs/$IMAGE_NAME:$IMAGE_TAG .
    
    - name: Push the Docker image
      run: |
        IMAGE_NAME=my-docker-image
        IMAGE_TAG=$(date +%Y%m%d%H%M%S)  # Use the same tag generated earlier
        docker push ghcr.io/cipherforge-labs/$IMAGE_NAME:$IMAGE_TAG
