name: Publish Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Log in to GitHub Packages
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build and Tag Docker Image
      env:
        IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/my-docker-image
      run: |
        LOWERCASE_IMAGE_NAME=$(echo $IMAGE_NAME | tr '[:upper:]' '[:lower:]')
        docker build -t $LOWERCASE_IMAGE_NAME:latest .
        docker tag $LOWERCASE_IMAGE_NAME:latest $LOWERCASE_IMAGE_NAME:$(date +%Y%m%d%H%M%S)

    - name: Push Docker Image to GitHub Packages
      env:
        IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/my-docker-image
      run: |
        LOWERCASE_IMAGE_NAME=$(echo $IMAGE_NAME | tr '[:upper:]' '[:lower:]')
        docker push $LOWERCASE_IMAGE_NAME:latest
        docker push $LOWERCASE_IMAGE_NAME:$(date +%Y%m%d%H%M%S)
