name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v4

    - name: Build the Docker image
      env:
        IMAGE_NAME: my-docker-image
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $IMAGE_NAME:$IMAGE_TAG .

    - name: Save Docker image as .tar
      env:
        IMAGE_NAME: my-docker-image
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker save -o docker-image.tar $IMAGE_NAME:$IMAGE_TAG

    - name: Upload Docker image artifact
      uses: actions/upload-artifact@v3
      with:
        name: docker-image
        path: docker-image.tar
